### PR TITLE
Add typescript as dependency

### PR DESCRIPTION
**Pull request by Tapped**

### CODE REVIEW

**Comment by sebbert** [comment]
The latest version of typescript is 3.6.3, is there a good reason to use 3.5.x?

**Comment by Tapped** [comment]
Yeah, forgot to mention that, but we get this otherwise. I'm not sure where the estree dependency is coming from, but probably typescript plugin for eslint.
```

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.6.3

Please only submit bug reports when using the officially supported version.

=============
```

**Comment by valgussev** [comment]
I'm a bit against adding stuff into this repo since it is annoying and time consuming to update it later. Official CRA does not have it as a dependency, why should we? Just install it as a devDep in the app

**Comment by Tapped** [comment]
Since the official one doesn't have typescript support. Today @cognite/react-scripts expects the user to install typescript as a global package. I should've mentioned that in the commit, so I'll fix that.

**Comment by sebbert** [comment]
Actually, it seems that they have typescript support now https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template-typescript

**Comment by Tapped** [comment]
> Just install it as a devDep in the app

We could do that as well, but then we should add it as a peer-dependency here.

**Comment by valgussev** [comment]
Correct, starting from cra-3 they fully support using both js and ts in one repo

**Comment by Tapped** [comment]
Interesting, so then CRA is just expecting typescript to be installed. I see

**Comment by Tapped** [comment]
I'll close this PR then, as this seems to be the standard in this case.

**Comment by sebbert** [comment]
Makes sense though, the TypeScript version only really matters to the code in your project

**Comment by Tapped** [comment]
Kind of, but eslint for typescript, expects typescript to be installed. So a peer-dependency would be nice to have, with this rule `>=3.2.1 <3.6.0`

**Comment by sebbert** [comment]
Good point, that would be helpful 👍

**Comment by Tapped** [comment]
Or I guess, not all CRA apps use typescript, and the typescript plugin for eslint isn't triggered in that case, so a peer-dependency may not be what we want.

**Pull request closed without merging**
