### PR TITLE
Add default node_path

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure if this is the best way to resolve this issue, but by default at least now it loads the /src folder.

### CODE REVIEW

**Comment by halvard-cognite** [comment]
The default branch is next, but the version we have published is from master.
The next branch has a lot of changes that are in beta on create-react-app so merging it might not be a good idea.

Any thoughts on this?

**Comment by ghost** [comment]
thats a good point, I will switch to master branch sorry! do you think changing the default value like this is fine?

**Comment by ghost** [comment]
also @halvard-cognite what should we do with the .piettierrc file?

```
{
  "trailingComma": "es5",
  "singleQuote": true
}
```

**Comment by halvard-cognite** [comment]
@dlcognite We should remove it, it's now part of the eslint config :)

**Comment by halvard-cognite** [comment]
@dlcognite I really don't know if we should do this.
Maybe we should spend 5 mins. discussing it.

**Pull request closed without merging**
